name: Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Pull Docker Image
      run: docker pull your-dockerhub-username/your-image-name:your-tag

    - name: Run Docker Container
      run: |
        docker run -d -p 8080:80 --name your-container-name your-dockerhub-username/your-image-name:your-tag
