name: Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  run-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Pull Docker Image
      run: docker pull jorritgeurts/dotnetapp:latest

    - name: Run Docker Container
      run: docker run -d -p 8080:80 jorritgeurts/dotnetapp:latest
