name: Run Docker Container

on:
  push:
    branches:
      - main

jobs:
  run-docker-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: Dockerfile
        context: .

    - name: Pull Docker image
      run: docker pull JorritGeurts/dotnetapp:latest

    - name: Run Docker container
      run: docker run -p 8080:80 -d --name galleon-container JorritGeurts/dotnetapp:latest

    - name: Show container status
      run: docker ps

    - name: Access the application
      run: echo "Access your application at http://localhost:8080"
