# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - galleon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://galleon.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9971ab7f11374d0893fda2730e87577b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4b43642d022d4b2eb723a4d0e676f318 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: galleon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9971ab7f11374d0893fda2730e87577b }}/dotnet:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'galleon'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fd0da2342d8342d88fee1da35878f6ff }}
        images: 'galleon.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9971ab7f11374d0893fda2730e87577b }}/dotnet:${{ github.sha }}'